name = "Real 1-20-1"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index-20260627.toml"
hash-format = "sha256"
hash = "8aec745fd87fc6a73fb8eb2f08225e6ee9ab155f1e70534dc4bee8bde18fbe9a"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
