name = "Real 1-20-1 Mac"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d2e1eb2aca0f67978cd0ed5aceac18e2c15f9903437cc5f5f5c5e2209781f86a"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
