name = "Real 1-20-1 Mac"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9e64f6e947fa2ce9df7ca58e752f211689844f53bdc6d96fbc33f9622dd086c0"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
