#PlayerAbilityLib configuration file
#
#If alwaysLogTamperWarnings is set to false, external update messages will be logged only once per game session
#Wed Feb 26 15:09:20 MSK 2025
alwaysLogTamperWarnings=true
